# Generated by Django 4.2.25 on 2025-11-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('duration', models.FloatField()),
                ('image', models.ImageField(upload_to='alerts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
